---
version: 2.0

references:
  stack_build: &stack_build
    docker:
      # https://github.com/haskell-works/stack-build/blob/master/minimal/Dockerfile
      - image: quay.io/haskell_works/stack-build-minimal
    steps:
      - checkout
      - run:
          name: Digest
          command: |
            echo -- "$STACK_ARGUMENTS" > rdigest
            git ls-files | xargs md5sum > sdigest
      - restore_cache:
          keys:
            - 1-{{ .Branch }}-{{ checksum "rdigest" }}-{{ checksum "sdigest" }}
            - 1-{{ .Branch }}-{{ checksum "rdigest" }}-
            - 1-{{ .Branch }}-
            - 1-master-
      - run:
          name: Dependencies
          command: make setup
          no_output_timeout: 120m
      - run:
          name: Build
          command: make build
      - save_cache:
          key: 1-{{ .Branch }}-{{ checksum "rdigest" }}-{{ checksum "sdigest" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Test
          command: make test
      - run:
          name: Lint
          command: |
            if [ "${LINT:-1}" -eq 0 ]; then
              echo "Skipping lint (LINT=0)" >&2
              exit 0
            fi

            make lint

jobs:
  build_8.0.2:
    <<: *stack_build
    environment:
      LINT: 0  # https://circleci.com/gh/pbrisbin/yesod-markdown/73
      STACK_ARGUMENTS: --stack-yaml stack-lts-9.21.yaml
  build_8.2.2:
    <<: *stack_build
    environment:
      STACK_ARGUMENTS: --resolver lts-11.19
  build:
    <<: *stack_build

  # Nightly is special: no caching. You'd be surprised how hard it is to
  # accomplish that while re-using the *stack_build reference.
  build_nightly:
    docker:
      - image: quay.io/haskell_works/stack-build-minimal
    steps:
      - checkout
      - run: make

workflows:
  version: 2
  builds:
    jobs:
      - build_8.0.2
      - build_8.2.2
      - build
      - build_nightly
